name: Build TUI for Linux x86_64 

on:
  push:
    branches: [ test_githubActions ]
  workflow_dispatch:


jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements-linux.txt ]; then pip install -r requirements-linux.txt; fi
  
      - name: Get TUI VersionName
        run: | 
          VERSION_NAME=$(python3 -c "import TUI.Version; print(TUI.Version.VersionName)")
          echo "TUI_VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Build with PyInstaller
        run: |
          pyinstaller --collect-all RO --collect-all TUI --collect-all Pmw \
            --collect-all PIL --collect-all twisted --collect-all astropy \
            --collect-all matplotlib --collect-all numpy --collect-all pygame \
            --collect-all scipy \
            --add-data TUI:TUI --add-data RO:RO \
            --icon TUI.icns --windowed --onefile tui.py
          mv dist/tui dist/tui-${{ env.TUI_VERSION_NAME }}-${{ runner.os }}-${{ runner.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: tui-${{ env.TUI_VERSION_NAME }}-${{ runner.os }}-${{ runner.arch }}
          path: dist/tui-${{ env.TUI_VERSION_NAME }}-${{ runner.os }}-${{ runner.arch }}
          archive: false
